package persistance.entities;


import java.util.HashSet;

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;


// Generated 8 sept. 2018 22:43:14 by Hibernate Tools 3.4.0.CR1

/**
 * Fournisseur generated by hbm2java
 */
@Entity
public class Fournisseur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
@Id
@Column(unique = true, nullable = false)
@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idfrs;
	private String nomfrs;
	private String mailContact;
	private String adressefrs;
	//@OneToMany(targetEntity=Kpimois.class, mappedBy="fournisseur", fetch=FetchType.LAZY,cascade=CascadeType.ALL)
	 @OneToMany(mappedBy = "fournisseur",fetch = FetchType.EAGER,cascade=CascadeType.ALL)
	   private Set<KpiSupplier> kpisupplier = new HashSet<KpiSupplier>(0);
	   
	public Fournisseur(Integer idfrs, String nomfrs, String mailContact,
			String adressefrs, Set<KpiSupplier> kpisupplier) {
		super();
		this.idfrs = idfrs;
		this.nomfrs = nomfrs;
		this.mailContact = mailContact;
		this.adressefrs = adressefrs;
		this.kpisupplier = kpisupplier;
	}
	public Fournisseur() {
		super();
		// TODO Auto-generated constructor stub
	}
	public Integer getIdfrs() {
		return idfrs;
	}
	public void setIdfrs(Integer idfrs) {
		this.idfrs = idfrs;
	}
	public String getNomfrs() {
		return nomfrs;
	}
	public void setNomfrs(String nomfrs) {
		this.nomfrs = nomfrs;
	}
	public String getMailContact() {
		return mailContact;
	}
	public void setMailContact(String mailContact) {
		this.mailContact = mailContact;
	}
	public String getAdressefrs() {
		return adressefrs;
	}
	public void setAdressefrs(String adressefrs) {
		this.adressefrs = adressefrs;
	}
	public Set<KpiSupplier> getKpisupplier() {
		return kpisupplier;
	}
	public void setKpisupplier(Set<KpiSupplier> kpisupplier) {
		this.kpisupplier = kpisupplier;
	}


	
	

}
