package persistance.entities;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

// Generated 8 sept. 2018 22:43:14 by Hibernate Tools 3.4.0.CR1

/**
 * Kpi generated by hbm2java
 */
@Entity
public class Kpi implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer idkpi;
	private String description;
	private int poids;
	
	//@OneToMany(targetEntity=Kpimois.class, mappedBy="kpi", fetch=FetchType.LAZY,cascade=CascadeType.ALL)
	 @OneToMany(mappedBy = "kpi",fetch = FetchType.EAGER,cascade=CascadeType.ALL)
	private Set<KpiSupplier> kpisupplier= new HashSet<KpiSupplier>(0);

	public Kpi() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Kpi(Integer idkpi, String description, int poids,
			Set<KpiSupplier> kpisupplier) {
		super();
		this.idkpi = idkpi;
		this.description = description;
		this.poids = poids;
		this.kpisupplier = kpisupplier;
	}

	public Integer getIdkpi() {
		return idkpi;
	}

	public void setIdkpi(Integer idkpi) {
		this.idkpi = idkpi;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getPoids() {
		return poids;
	}

	public void setPoids(int poids) {
		this.poids = poids;
	}

	public Set<KpiSupplier> getKpisupplier() {
		return kpisupplier;
	}

	public void setKpisupplier(Set<KpiSupplier> kpisupplier) {
		this.kpisupplier = kpisupplier;
	}

	
}
